### PR TITLE
[Issue 2117] Fix unused warnings in RocketMQ examples

### LINKED ISSUE #2117: [Doc📝] Fix(supress) the warnings comes in by runnung `cargo test`.
### Search before creation

- [X] I had searched in the [issues](https://github.com/mxsm/rocketmq-rust/issues) and found no similar issues.

## Warning 1
Screenshot from 2025-01-06 10-46-11
## Warning 2
Screenshot from 2025-01-06 10-45-36
## Warning 3
Screenshot from 2025-01-06 10-46-00
## Warning 4
Screenshot from 2025-01-06 10-46-32

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by nakul-py**
### Description:
This PR addresses several compiler warnings related to unused imports, variables, and redundant mutability in the RocketMQ examples. The changes clean up the code without altering functionality:

  - Removed unused imports and redundant comparisons.
  -  Prefixed unused variables with _ to suppress warnings.
   - Removed unnecessary mut in variable declarations.

- Fixes #2117 

## Summary by CodeRabbit

- **Code Clarity**
  - Updated transaction producer method parameter naming to indicate unused arguments
  - Modified locking mechanism in transaction listener to clarify read-only access

- **Testing**
  - Simplified IP address generation test validation (potential reduction in test rigor)

### CODE REVIEW

File: rocketmq-client/examples/transaction/transaction_producer.rs [hunk 1]
```diff
@@ -85,7 +85,7 @@ impl TransactionListener for TransactionListenerImpl {
     fn execute_local_transaction(
         &self,
         msg: &Message,
-        arg: Option<&(dyn Any + Send + Sync)>,
+        _arg: Option<&(dyn Any + Send + Sync)>,
```
Comment (nakul-py) [inline rocketmq-client/examples/transaction/transaction_producer.rs:88]: LGTM or no  any warnings came now.

**Review by nakul-py — COMMENTED** [review]
LGTM

**Review by mxsm — APPROVED** [review]
LGTM
