### PR TITLE
[ISSUE #2115]Allow unused imports in ordermessage_consumer file

### LINKED ISSUE #2115: [Bug🐛] Allow unused imports in `ordermessage_consumer.rs`
### Before Creating the Bug Report

- [X] I found a bug, not just asking a question, which should be created in [GitHub Discussions](https://github.com/mxsm/rocketmq-rust/discussions).

- [X] I have searched the [GitHub Issues](https://github.com/mxsm/rocketmq-rust/issues) and [GitHub Discussions](https://github.com/mxsm/rocketmq-rust/discussions)  of this repository and believe that this is not a duplicate.

- [X] I have confirmed that this bug belongs to the current repository, not other repositories of RocketMQ.

### Runtime platform environment

_No response_

### RocketMQ Rust version

_No response_

### Rust Version

_No response_

### Describe the Bug

_No response_

### Steps to Reproduce

- 1. Run `cargo build`
- 2. Run `cargo test`

### What Did You Expect to See?

_No response_

### What Did You See Instead?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nakul-py**
### Which Issue(s) This PR Fixes(Closes)

- [Bug🐛] Allow unused imports in ordermessage_consumer.rs

- Fixes #2115 

## Summary by CodeRabbit

- **Chores**
	- Reorganized import statements in the order message consumer example.
	- Added an unused import with a suppression attribute.

### CODE REVIEW

**Review by nakul-py — COMMENTED** [review]
This allows unused impots and supress the warning or else
 LGTM!

**Review by nakul-py — COMMENTED** [review]
Now it won't warn the user or anything about this imports

**Review by mxsm — CHANGES_REQUESTED** [review]
@nakul-py Please fix code style with rust command

File: rocketmq-client/examples/ordermessage/ordermessage_consumer.rs [hunk 1]
```diff
@@ -18,6 +18,7 @@ use std::sync::atomic::AtomicI64;
 use std::sync::Arc;
 
 use rocketmq_client_rust::consumer::default_mq_push_consumer::DefaultMQPushConsumer;
+#[allow(unused_imports)]
```
Comment (nakul-py) [inline rocketmq-client/examples/ordermessage/ordermessage_consumer.rs:21]: hey @mxsm Is this looks good?
